#!/usr/bin/env node
// Produces the two inputs vsce needs that are not source files, both into dist/:
//
//   assets/icon.svg -> dist/icon.png   the Marketplace accepts raster icons only
//   README.md       -> dist/README.md  the Marketplace rejects SVG in a README
//
// Both are build artifacts: generated by `vscode:prepublish`, never committed, never
// edited by hand.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Resvg } from '@resvg/resvg-js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dist = resolve(root, 'dist');

mkdirSync(dist, { recursive: true });

// --- icon ---------------------------------------------------------------------
// 128x128 is the documented minimum; 256 keeps it crisp on hidpi listings. The SVG
// deliberately contains no <text>, and system fonts are disabled, so the output is
// identical on every machine.
const SIZE = 256;

const rendered = new Resvg(readFileSync(resolve(root, 'assets/icon.svg'), 'utf8'), {
  fitTo: { mode: 'width', value: SIZE },
  font: { loadSystemFonts: false },
}).render();

if (rendered.width !== SIZE || rendered.height !== SIZE) {
  throw new Error(`expected a ${SIZE}x${SIZE} icon, rendered ${rendered.width}x${rendered.height}`);
}

const png = rendered.asPng();
writeFileSync(resolve(dist, 'icon.png'), png);
console.log(`icon:   ${SIZE}x${SIZE}, ${png.length} bytes -> dist/icon.png`);

// --- readme -------------------------------------------------------------------
// The icon block is shown on GitHub and dropped here: vsce refuses an SVG anywhere
// in a README, and the Marketplace renders the icon in the page header anyway.
const ICON_BLOCK = /^<!-- icon:begin[\s\S]*?<!-- icon:end -->\n\n/m;

const readme = readFileSync(resolve(root, 'README.md'), 'utf8');

if (!ICON_BLOCK.test(readme)) {
  throw new Error('README.md has no <!-- icon:begin --> … <!-- icon:end --> block to strip');
}

const stripped = readme.replace(ICON_BLOCK, '');
writeFileSync(resolve(dist, 'README.md'), stripped);
console.log(`readme: icon block stripped, ${stripped.length} bytes -> dist/README.md`);
